### ISSUE TITLE
Flaky test: tests/chainer_tests/links_tests/connection_tests/test_deconvolution_2d.py

### ISSUE THREAD

**Issue by hvy** [chainer/chainer#7693]
https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1497/TEST=chainer-py2,label=mn1-p100/testReport/junit/tests.chainer_tests.links_tests.connection_tests.test_deconvolution_2d/TestDeconvolution2DParameterShapePlaceholder_param_16_%7Buse_cudnn='always',%20nobias=True,%20deconv_args=((None,%202,%203,%202,%201),%20%7B%7D)%7D/test_backward_gpu/

**Comment by emcastillo** [comment]
This seems related to #7695 so I will take over it.

**Comment by emcastillo** [comment]
Update CuDNN to 5.1 for python2 jenkins tests should solve this issue.
@kmaehashi volunteered to do it.

**Comment by kmaehashi** [comment]
Fix in https://github.com/chainer/chainer-test/pull/514

**Comment by niboshi** [comment]
Reoccurred in convolution_nd. Most likely not fixed yet.
https://github.com/chainer/chainer/issues/7695#issuecomment-517100236

**Comment by hvy** [comment]
Reoccurred https://jenkins.preferred.jp/job/chainer/job/chainer_pr/1930/
It's the functions and not the link test though.

**Comment by hvy** [comment]
Let me reopen this ticker.

**Comment by emcastillo** [comment]
Pending the backport, master already merged.
